# Generated by Django 4.0.3 on 2022-08-03 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('hostel', models.CharField(max_length=100)),
                ('certificate', models.ImageField(null=True, upload_to='Student-Docs/certs')),
                ('result_slip', models.ImageField(null=True, upload_to='Student-Docs/slips')),
                ('letter', models.ImageField(null=True, upload_to='Student-Docs/letters')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Academic',
                'ordering': ['year', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=100)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('scholar', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='students.academicprofile')),
            ],
            options={
                'verbose_name_plural': "Student's Registered Units",
                'ordering': ['scholar'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('phone_no', models.CharField(max_length=10)),
                ('residence', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=60)),
                ('ethnicity', models.CharField(max_length=40)),
                ('pic', models.ImageField(default='default.jpg', upload_to='Student-Dps/')),
                ('bio', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students',
                'ordering': ['student'],
            },
        ),
        migrations.AddField(
            model_name='academicprofile',
            name='academic',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
    ]
