# Generated by Django 4.0.3 on 2022-08-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprofile',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
    ]
