# Generated by Django 4.0.3 on 2022-08-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_academicprofile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='confirmed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='units',
            name='unit_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
