# Generated by Django 4.0.3 on 2022-08-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_units_confirmed_units_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='unit_type',
            field=models.CharField(max_length=50),
        ),
    ]
