# Generated by Django 4.0.3 on 2022-08-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_units_unit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='unit_type',
            new_name='study_mode',
        ),
    ]
