# Generated by Django 4.0.3 on 2022-08-08 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_unit_type_units_study_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.FileField(upload_to='Assignments/')),
                ('unit', models.CharField(max_length=100)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('stud', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='students.academicprofile')),
            ],
            options={
                'ordering': ['stud'],
            },
        ),
    ]
