# Generated by Django 4.0.3 on 2022-08-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_academicprofile_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicprofile',
            old_name='credit',
            new_name='credits',
        ),
    ]
